version: "3.8"

services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=uptime_db
      - MYSQL_ROOT_PASSWORD=tester1234
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  auth_service:
    build: ./api/auth
    ports: 
      - 9000:9000

volumes:
  db:
    driver: local
